(function(){
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let page='dashboard';
const seed=[{id:1,name:'Headphone Bluetooth Bass Pro',price:249000,category:'Elektronik',location:'Jakarta',emoji:'🎧',sold:'1,2rb',discount:40,flash:true,sellerId:'SHOP-1',stock:24},{id:2,name:'Smartwatch Layar AMOLED',price:389000,category:'Elektronik',location:'Bandung',emoji:'⌚',sold:'856',discount:35,flash:true,sellerId:'SHOP-1',stock:15},{id:3,name:'Sepatu Lari Ringan Unisex',price:215000,category:'Olahraga',location:'Surabaya',emoji:'👟',sold:'2,3rb',discount:50,flash:true,sellerId:'SHOP-2',stock:31},{id:4,name:'Paket Skincare Brightening',price:129000,category:'Kecantikan',location:'Jakarta Selatan',emoji:'🧴',sold:'3,1rb',discount:30,flash:true,sellerId:'SHOP-2',stock:18}];
function products(){try{return JSON.parse(localStorage.getItem('samudra_products')||'null')||seed}catch(e){return seed}}function saveProducts(v){localStorage.setItem('samudra_products',JSON.stringify(v))}function data(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return[]}}function shops(){return data('samudra_shops')}
const titles={dashboard:'Dashboard',orders:'Pesanan',products:'Semua Produk',sellers:'Seller & Toko',users:'User',categories:'Kategori',reports:'Laporan',settings:'Pengaturan'};
function render(){if(!$('adminContent'))return; $('pageTitle').textContent=titles[page];document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const c=$('adminContent');if(page==='dashboard')dashboard(c);else if(page==='products')productPage(c);else if(page==='orders')orderPage(c);else if(page==='sellers')sellerPage(c);else if(page==='users')userPage(c);else if(page==='categories')categoryPage(c);else if(page==='reports')reportPage(c);else settingsPage(c)}
function dashboard(c){const p=products(),o=data('samudra_orders'),s=shops(),u=data('samudra_users'),r=o.reduce((a,x)=>a+Number(x.total||0),0),pending=s.filter(x=>x.status==='pending').length;c.innerHTML=`<div class="stats stat-grid"><div class="card"><small>Total Produk</small><h2>${p.length}</h2><span>Semua seller</span></div><div class="card"><small>Total Pesanan</small><h2>${o.length}</h2><span>Order tercatat</span></div><div class="card"><small>Toko Aktif</small><h2>${s.filter(x=>x.status==='active').length}</h2><span>${pending} menunggu verifikasi</span></div><div class="card"><small>Revenue Demo</small><h2>${money(r)}</h2><span>Frontend prototype</span></div></div><div style="display:grid;grid-template-columns:1.4fr .8fr;gap:16px;margin-top:16px"><div class="card"><h3>Marketplace overview</h3><p style="color:#718899;line-height:1.7;font-size:13px">Satu akun dapat menjadi customer sekaligus seller. Admin memverifikasi toko, mengelola semua produk, user, order, dan kategori.</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px"><div style="padding:14px;background:#f3f8fb;border-radius:12px"><b>${pending}</b><small style="display:block;color:#7890a1">Pending Seller</small></div><div style="padding:14px;background:#f3f8fb;border-radius:12px"><b>${u.length}</b><small style="display:block;color:#7890a1">User</small></div><div style="padding:14px;background:#f3f8fb;border-radius:12px"><b>${o.filter(x=>x.status!=='Selesai').length}</b><small style="display:block;color:#7890a1">Open Order</small></div></div></div><div class="card"><h3>Quick Actions</h3><button class="quick" data-go="sellers">♙ Verifikasi Seller</button><button class="quick" data-go="products">＋ Kelola Produk</button><button class="quick" data-go="orders">▤ Cek Pesanan</button></div></div>`;c.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{page=b.dataset.go;render()})}
function productPage(c){const p=products();c.innerHTML=`<div class="card"><div style="display:flex;justify-content:space-between;align-items:center"><div><h3>Semua Produk</h3><p style="color:#7890a1;font-size:12px">Admin dapat mengelola semua produk.</p></div><button id="add" class="primary">＋ Tambah Produk</button></div><div style="overflow:auto;margin-top:15px"><table><thead><tr><th>Produk</th><th>Shop ID</th><th>Kategori</th><th>Harga</th><th>Aksi</th></tr></thead><tbody>${p.map(x=>`<tr><td>${esc(x.emoji)} ${esc(x.name)}</td><td>${esc(x.sellerId||'—')}</td><td>${esc(x.category)}</td><td>${money(x.price)}</td><td><button data-edit="${x.id}">Edit</button> <button data-del="${x.id}">Hapus</button></td></tr>`).join('')}</tbody></table></div></div>`;$('add').onclick=()=>editProduct();c.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(+b.dataset.edit));c.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{saveProducts(p.filter(x=>x.id!==+b.dataset.del));render()})}
function editProduct(id){const p=products(),o=p.find(x=>x.id===id)||{};const name=prompt('Nama produk',o.name||'');if(!name)return;const price=Number(prompt('Harga',o.price||0));if(!price)return;const category=prompt('Kategori',o.category||'Elektronik')||'Elektronik';const sellerId=prompt('Shop ID',o.sellerId||'SHOP-1')||'SHOP-1';const item={...o,id:id||Date.now(),name,price,category,sellerId,emoji:o.emoji||'📦',location:o.location||'Indonesia',sold:o.sold||'0',discount:Number(o.discount||0),flash:!!o.flash,stock:Number(o.stock||0)};if(id)p[p.findIndex(x=>x.id===id)]=item;else p.push(item);saveProducts(p);render()}
function orderPage(c){const o=data('samudra_orders');c.innerHTML=`<div class="card"><h3>Semua Pesanan</h3><table><thead><tr><th>Order</th><th>Pembeli</th><th>Total</th><th>Status</th></tr></thead><tbody>${o.length?o.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.name||'Customer')}</td><td>${money(x.total)}</td><td>${esc(x.status||'Menunggu pembayaran')}</td></tr>`).join(''):'<tr><td colspan="4">Belum ada order.</td></tr>'}</tbody></table></div>`}
function sellerPage(c){const s=shops();c.innerHTML=`<div class="card"><h3>Seller & Verifikasi Toko</h3><p style="color:#7890a1">Admin memutuskan apakah pengajuan toko dapat menjadi Seller Center aktif.</p><div style="overflow:auto"><table><thead><tr><th>Pemilik</th><th>Toko</th><th>Domain</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${s.length?s.map(x=>`<tr><td>${esc(x.userId)}</td><td>${esc(x.name)}</td><td>${esc(x.domain)}</td><td><b>${esc(x.status)}</b></td><td>${x.status==='pending'?`<button data-approve="${x.id}">Approve</button> <button data-reject="${x.id}">Reject</button>`:x.status==='active'?`<button data-suspend="${x.id}">Suspend</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="5">Belum ada pengajuan toko.</td></tr>'}</tbody></table></div></div>`;
c.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>updateShop(b.dataset.approve,'active'));c.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>updateShop(b.dataset.reject,'rejected'));c.querySelectorAll('[data-suspend]').forEach(b=>b.onclick=()=>updateShop(b.dataset.suspend,'suspended'))}
function updateShop(id,status){const ss=shops(),i=ss.findIndex(x=>x.id===id);if(i<0)return;ss[i].status=status;localStorage.setItem('samudra_shops',JSON.stringify(ss));const users=data('samudra_users'),ui=users.findIndex(u=>u.id===ss[i].userId);if(ui>=0){users[ui].shop={id:ss[i].id,name:ss[i].name,domain:ss[i].domain,status};localStorage.setItem('samudra_users',JSON.stringify(users))}const sess=JSON.parse(localStorage.getItem('samudra_session')||'null');if(sess&&sess.id===ss[i].userId){sess.shop={id:ss[i].id,name:ss[i].name,domain:ss[i].domain,status};localStorage.setItem('samudra_session',JSON.stringify(sess))}render()}
function userPage(c){const u=data('samudra_users');c.innerHTML=`<div class="card"><h3>User</h3><table><thead><tr><th>User</th><th>Email</th><th>Toko</th><th>Status</th></tr></thead><tbody>${u.length?u.map(x=>`<tr><td>${esc(x.name||'—')}</td><td>${esc(x.email)}</td><td>${esc(x.shop?.status||'none')}</td><td>${esc(x.status||'Aktif')}</td></tr>`).join(''):'<tr><td colspan="4">Belum ada user terdaftar.</td></tr>'}</tbody></table></div>`}
function categoryPage(c){let a=JSON.parse(localStorage.getItem('samudra_categories')||'["Elektronik","Fashion","Rumah Tangga","Kecantikan","Ibu & Bayi","Olahraga","Otomotif","Buku"]');c.innerHTML=`<div class="card"><h3>Kategori</h3><div style="display:flex;gap:8px;margin:15px 0"><input id="newCat" placeholder="Nama kategori" style="flex:1"><button id="addCat">Tambah</button></div><div style="display:flex;gap:8px;flex-wrap:wrap">${a.map((x,i)=>`<span style="padding:8px 11px;background:#edf6fa;border-radius:99px;font-size:11px">${esc(x)} <button data-c="${i}">×</button></span>`).join('')}</div></div>`;$('addCat').onclick=()=>{const v=$('newCat').value.trim();if(v&&!a.includes(v)){a.push(v);localStorage.setItem('samudra_categories',JSON.stringify(a));render()}};c.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{a.splice(+b.dataset.c,1);localStorage.setItem('samudra_categories',JSON.stringify(a));render()})}
function reportPage(c){const p=products(),o=data('samudra_orders'),r=o.reduce((a,x)=>a+Number(x.total||0),0);c.innerHTML=`<div class="stats stat-grid"><div class="card"><small>Revenue</small><h2>${money(r)}</h2></div><div class="card"><small>Orders</small><h2>${o.length}</h2></div><div class="card"><small>Produk</small><h2>${p.length}</h2></div><div class="card"><small>Avg Order</small><h2>${money(o.length?r/o.length:0)}</h2></div></div>`}
function settingsPage(c){c.innerHTML=`<div class="card"><h3>Pengaturan Marketplace</h3><p style="color:#7890a1">Pengaturan demo frontend. Backend production akan memindahkan autentikasi, verifikasi dokumen, dan permission ke server.</p><button id="resetDemo">Reset Data Demo</button></div>`;$('resetDemo').onclick=()=>{if(confirm('Reset data demo?')){['samudra_products','samudra_orders','samudra_users','samudra_shops'].forEach(k=>localStorage.removeItem(k));location.reload()}}}
window.initModernAdmin=render;document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{page=b.dataset.page;render();document.querySelector('.sidebar')?.classList.remove('open')});$('refreshAdmin')?.addEventListener('click',render);$('mobileMenu')?.addEventListener('click',()=>document.querySelector('.sidebar')?.classList.toggle('open'));if(document.getElementById('adminConsole')&&!document.getElementById('adminConsole').hidden)render();
})();
