const session=JSON.parse(localStorage.getItem('samudra_session')||'null');if(!session)location.href='auth.html';
const $=id=>document.getElementById(id);const getShop=()=>{const shops=JSON.parse(localStorage.getItem('samudra_shops')||'[]');return shops.find(x=>x.userId===session.id)||null};
$('profileName').textContent=session?.name||'Pengguna';$('profileEmail').textContent=session?.email||'';$('avatar').textContent=(session?.name||'U').charAt(0).toUpperCase();
const pages={profile,orders,address,wishlist,security};function render(p='profile'){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));pages[p]($('customerPage'));}
function sellerAction(){const s=JSON.parse(localStorage.getItem('samudra_session')||'null');if(s?.shop?.status==='active')return `<a class="seller-link" href="seller.html">🏪 Seller Center →</a>`;if(s?.shop?.status==='pending')return `<a class="seller-link" href="buka-toko.html">⏳ Status Toko: Menunggu Verifikasi →</a>`;return `<a class="seller-link" href="buka-toko.html">🏪 Buka Toko Gratis →</a>`}
function profile(c){c.innerHTML=`<div class="panel"><h3>Profil Saya</h3><div class="form-grid"><div class="field"><label>Nama Lengkap</label><input id="name" value="${session.name||''}"></div><div class="field"><label>Email</label><input value="${session.email||''}" disabled></div><div class="field"><label>No. Handphone</label><input id="phone" placeholder="08xxxxxxxxxx" value="${session.phone||''}"></div><div class="field"><label>Tanggal Lahir</label><input type="date" id="birth" value="${session.birth||''}"></div></div><button class="save" id="save">Simpan Perubahan</button></div><div class="panel seller-upgrade"><h3>Belanja + Berjualan dari Satu Akun</h3><p>Anda tetap memakai akun yang sama sebagai customer. Jika memiliki toko aktif, Anda dapat berpindah ke Seller Center tanpa login ulang.</p>${sellerAction()}</div>`;$('save').onclick=()=>{session.name=$('name').value.trim();session.phone=$('phone').value.trim();session.birth=$('birth').value;localStorage.setItem('samudra_session',JSON.stringify(session));$('profileName').textContent=session.name;toast('Profil berhasil diperbarui.')}}
function orders(c){const all=JSON.parse(localStorage.getItem('samudra_orders')||'[]');const o=all.filter(x=>x.customerId===session.id||(!x.customerId&&x.id===JSON.parse(localStorage.getItem('samudra_last_order')||'null')?.id));c.innerHTML=`<div class="panel"><h3>Pesanan Saya</h3>${o.length?`<div class="list">${o.slice().reverse().map(x=>`<div class="row"><div><b>${x.id}</b><div style="color:#70879A;margin-top:5px">${x.name||session.name} · ${x.address||'Alamat belum tercatat'}</div></div><span class="tag">${x.status}</span></div>`).join('')}</div>`:'<div class="row">Belum ada pesanan. <a href="index.html" style="color:#0A4174;font-weight:700">Belanja sekarang →</a></div>'}</div>`}
function address(c){c.innerHTML=`<div class="panel"><h3>Alamat Saya</h3><div class="row"><div><b>Alamat utama</b><div style="color:#70879A;margin-top:5px">Tambahkan alamat pengiriman untuk checkout lebih cepat.</div></div><button class="save" onclick="alert('Modul alamat dapat dihubungkan ke database pada backend.')">Tambah</button></div></div>`}
function wishlist(c){c.innerHTML='<div class="panel"><h3>Wishlist</h3><div class="row">Wishlist masih kosong. Simpan produk favoritmu dari marketplace.</div></div>'}
function security(c){c.innerHTML=`<div class="panel"><h3>Keamanan Akun</h3><div class="row"><div><b>Password</b><div style="color:#70879A;margin-top:5px">Password tersimpan aman di backend pada versi production.</div></div><button class="save" id="changePassword">Ubah</button></div></div>`;$('changePassword').onclick=()=>alert('Perubahan password akan menggunakan API backend pada versi production.')}
function toast(msg){let t=document.createElement('div');t.textContent=msg;t.style='position:fixed;right:20px;bottom:20px;background:#102b3f;color:#fff;padding:12px 16px;border-radius:10px;z-index:99';document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>render(b.dataset.page));$('editProfile').onclick=()=>render('profile');$('logout').onclick=()=>{localStorage.removeItem('samudra_session');location.href='index.html'};render();
