const session=JSON.parse(localStorage.getItem('samudra_session')||'null');
if(!session||!session.shop||session.shop.status!=='active'){location.href=session?.shop?.status==='pending'?'buka-toko.html':'index.html'}
const $=id=>document.getElementById(id),rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0),shopId=session?.shop?.id;
const seed=[{id:1,name:'Headphone Bluetooth Bass Pro',price:249000,category:'Elektronik',location:'Jakarta',emoji:'🎧',sold:'1,2rb',discount:40,flash:true,sellerId:'SHOP-1'},{id:2,name:'Smartwatch Layar AMOLED',price:389000,category:'Elektronik',location:'Bandung',emoji:'⌚',sold:'856',discount:35,flash:true,sellerId:'SHOP-1'},{id:3,name:'Sepatu Lari Ringan Unisex',price:215000,category:'Olahraga',location:'Surabaya',emoji:'👟',sold:'2,3rb',discount:50,flash:true,sellerId:'SHOP-2'},{id:4,name:'Paket Skincare Brightening',price:129000,category:'Kecantikan',location:'Jakarta Selatan',emoji:'🧴',sold:'3,1rb',discount:30,flash:true,sellerId:'SHOP-2'}];
function all(){try{const p=JSON.parse(localStorage.getItem('samudra_products')||'null');return p||seed}catch(e){return seed}}function save(v){localStorage.setItem('samudra_products',JSON.stringify(v))}function mine(){return all().filter(x=>x.sellerId===shopId||(shopId==='SHOP-1'&&x.sellerId==='SEL-1'))}function orders(){try{return JSON.parse(localStorage.getItem('samudra_orders')||'[]')}catch(e){return[]}}
const titles={dashboard:'Dashboard',products:'Produk Saya',orders:'Pesanan Masuk',finance:'Keuangan',store:'Toko Saya',settings:'Pengaturan'};let page='dashboard';$('sellerName').textContent=session.shop.name||session.name;$('sellerName').title=session.email;
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});$('logout').onclick=()=>{localStorage.removeItem('samudra_session');location.href='index.html'};
function render(){document.getElementById('title').textContent=titles[page];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const c=$('content');if(page==='dashboard')dashboard(c);else if(page==='products')products(c);else if(page==='orders')ordersPage(c);else if(page==='finance')finance(c);else if(page==='store')store(c);else settings(c)}
function dashboard(c){const p=mine(),o=orders().filter(x=>(x.items||[]).some(i=>i.sellerId===shopId));const rev=o.reduce((a,x)=>a+Number(x.total||0),0);c.innerHTML=`<div class="stats"><div class="card stat"><small>Produk Saya</small><h2>${p.length}</h2><span>Produk toko aktif</span></div><div class="card stat"><small>Pesanan Masuk</small><h2>${o.length}</h2><span>Pesanan terkait toko</span></div><div class="card stat"><small>Stok Produk</small><h2>${p.reduce((a,x)=>a+Number(x.stock||0),0)}</h2><span>Total stok katalog</span></div><div class="card stat"><small>Revenue Demo</small><h2>${rupiah(rev)}</h2><span>Prototype</span></div></div><div class="card" style="margin-top:16px"><h3>Selamat datang di Seller Center</h3><p class="muted">Kelola hanya produk milik <b>${session.shop.name}</b>. Akun ini tetap bisa digunakan untuk belanja sebagai customer.</p><a href="index.html" class="primary" style="display:inline-block;text-decoration:none;margin-top:10px">← Kembali Belanja</a></div>`}
function products(c){const p=mine();c.innerHTML=`<div class="card"><button class="add" id="add">＋ Tambah Produk</button><h3>Produk Saya</h3><p class="muted">Semua perubahan dibatasi pada <b>sellerId = ${shopId}</b>.</p><div class="grid">${p.map(x=>`<div class="product"><div class="thumb">${x.emoji}</div><h4>${x.name}</h4><div class="price">${rupiah(x.price)}</div><div class="muted">${x.category} · Stok ${x.stock??0}</div><div class="actions"><button data-edit="${x.id}">Edit</button><button class="danger" data-del="${x.id}">Hapus</button></div></div>`).join('')||'<div class="empty">Belum ada produk.</div>'}</div></div>`;$('add').onclick=()=>promptProduct();c.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>promptProduct(Number(b.dataset.edit)));c.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.del),arr=all(),item=arr.find(x=>x.id===id);if(!item||item.sellerId!==shopId)return alert('Akses ditolak: produk bukan milik toko ini.');save(arr.filter(x=>x.id!==id));render()})}
function promptProduct(id){const arr=all(),old=arr.find(x=>x.id===id);if(id&&old?.sellerId!==shopId)return alert('Akses ditolak.');const name=prompt('Nama produk',old?.name||'');if(!name)return;const price=Number(prompt('Harga',old?.price||0));if(!price)return;const stock=Number(prompt('Stok',old?.stock||0));const category=prompt('Kategori',old?.category||'Elektronik')||'Elektronik';const emoji=prompt('Emoji',old?.emoji||'📦')||'📦';const item={...old,id:id||Date.now(),name,price,stock,category,location:old?.location||'Indonesia',emoji,sold:old?.sold||'0',discount:Number(old?.discount||0),flash:!!old?.flash,sellerId:shopId};if(id)arr[arr.findIndex(x=>x.id===id)]=item;else arr.push(item);save(arr);render()}
function ordersPage(c){const o=orders().filter(x=>(x.items||[]).some(i=>i.sellerId===shopId));c.innerHTML=`<div class="card"><h3>Pesanan Masuk</h3><table class="table"><thead><tr><th>Order</th><th>Pembeli</th><th>Total</th><th>Status</th></tr></thead><tbody>${o.length?o.map(x=>`<tr><td>${x.id}</td><td>${x.name||'Customer'}</td><td>${rupiah(x.total)}</td><td>${x.status||'—'}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">Belum ada pesanan untuk toko ini.</td></tr>'}</tbody></table></div>`}
function finance(c){const rev=orders().filter(x=>(x.items||[]).some(i=>i.sellerId===shopId)).reduce((a,x)=>a+Number(x.total||0),0);c.innerHTML=`<div class="stats"><div class="card stat"><small>Gross Revenue</small><h2>${rupiah(rev)}</h2></div><div class="card stat"><small>Perkiraan Saldo</small><h2>${rupiah(rev*.9)}</h2></div></div>`}
function store(c){const shops=JSON.parse(localStorage.getItem('samudra_shops')||'[]');const sh=shops.find(x=>x.id===shopId)||{};c.innerHTML=`<div class="card"><h3>Toko Saya</h3><p class="muted">Informasi toko yang sudah diverifikasi.</p><label class="muted">Nama Toko<input id="storeName" style="display:block;width:100%;padding:11px;margin-top:7px;border:1px solid #dce7ed;border-radius:9px" value="${sh.name||session.shop.name}"></label><label class="muted" style="display:block;margin-top:12px">Domain<input disabled style="display:block;width:100%;padding:11px;margin-top:7px;border:1px solid #dce7ed;border-radius:9px" value="${sh.domain||session.shop.domain}"></label><button class="primary" id="saveStore" style="margin-top:12px">Simpan</button></div>`;$('saveStore').onclick=()=>{sh.name=$('storeName').value.trim();const i=shops.findIndex(x=>x.id===shopId);if(i>=0)shops[i]=sh;localStorage.setItem('samudra_shops',JSON.stringify(shops));session.shop.name=sh.name;localStorage.setItem('samudra_session',JSON.stringify(session));$('sellerName').textContent=sh.name;alert('Profil toko disimpan.')}}
function settings(c){c.innerHTML=`<div class="card"><h3>Pengaturan</h3><p class="muted">Pengaturan notifikasi, password, payout, dan integrasi akan menggunakan backend pada versi production.</p></div>`}
render();
